# Generated by Django 2.2.4 on 2019-08-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190814_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
