# Generated by Django 2.2.4 on 2019-08-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190815_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='about',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
